name: 'Pull requests: master'

on:
  pull_request:
    branches:
      - master

jobs:
  check_release_name:
    name: Check release name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        id: version
        run: |
          echo "::set-output name=version::${{github.event.pull_request.title}}"
      - shell: bash
        id: validate
        run: |
          VERSION='Release 1.0.0 yay.'
          if [[ $VERSION =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "::set-output name=version::${BASH_REMATCH[1]}"
          else
            exit 1
          fi
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            **Merging this request will create release:**  
            Release name: Release ${{steps.validate.outputs.version}}  
            Tag: `${{steps.validate.outputs.version}}`

            _Don't edit the merge commit message._
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: Pull requests name is incorrect. Please include `[(\d+\.\d+\.\d+)]`.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure()
