name: 'Pull requests: master'

on:
  pull_request:
    branches:
      - master

jobs:
  check_release_name:
    name: Check release name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        id: version
        run: |
          echo "::set-output name=version::${{github.event.pull_request.title}}"
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: '${{steps.version.outputs.version}}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
