name: 'Pull requests: master'

on:
  pull_request:
    branches:
      - master

jobs:
  check_release_name:
    name: Check release name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        id: version
        run: |
          echo "::set-output name=version::${{github.event.pull_request.title}}"
      - shell: bash
        id: validate
        run: |
          if [[ ${{steps.version.outputs.version}} =~ (\d+\.\d+\.\d+) ]]; then
            echo ${BASH_REMATCH[1]}
          fi
      # - uses: thollander/actions-comment-pull-request@master
      #   with:
      #     message: '${{steps.validate.outputs.version}}'
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
