name: 'push: master'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        id: validate
        run: |
          VERSION='${{github.event.head_commit.message}}'
          if [[ $VERSION =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "::set-output name=version::${BASH_REMATCH[1]}"
          else
            exit 1
          fi
      - shell: bash
        name: Make tag test.
        run: |
          git tag ${{steps.validate.outputs.version}}
          git tag -d ${{steps.validate.outputs.version}}
      - shell: bash
        id: changelog
        run: |
          git fetch --prune --unshallow
          yarn install --production=false
          description=$(yarn run --silent changelog --from=1.1.0 | sed -e 's/^## .*$//')
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=body::${description}"
        env:
          GITHUB_AUTH: ${{ secrets.LERNA_CHANGELOG_GITHUB_AUTH }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.validate.outputs.version}}
          release_name: Version ${{steps.validate.outputs.version}}
          body: ${{steps.changelog.outputs.body}}
          draft: false
          prerelease: false
