name: 'push: master'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        run: |
          git log
      - shell: bash
        id: version
        run: |
          echo "::set-output name=body::$RANDOM$RANDOM$RANDOM"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.body}}
          release_name: Version ${{steps.version.outputs.body}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
    env:
      VERSION: ""
