name: 'push: master'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        run: |
          echo $RANDOM$RANDOM$RANDOM > version.txt
      - shell: bash
        run: |
          cat version.txt | read version
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{version}}
          release_name: Release ${{version}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
