name: 'push: master'

on: [push]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        run: |
          echo $RANDOM$RANDOM$RANDOM > version.txt
      - shell: bash
        run: |
          cat version.txt | read version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{version}}
        with:
          tag_name: ${{VERSION}}
          release_name: ${{VERSION}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
