name: 'push: master'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        id: validate
        run: |
          VERSION='${{github.event.head_commit.message}}'
          if [[ $VERSION =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "::set-output name=version::${BASH_REMATCH[1]}"
          else
            exit 1
          fi
      - shell: bash
        name: Make tag test.
        run: |
          git tag ${{steps.validate.outputs.version}}
          git tag -d ${{steps.validate.outputs.version}}
      - shell: bash
        id: changelog
        run: |
          yarn run changelog | read NOTE
          echo "::set-output name=note::$NOTE"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.validate.outputs.version}}
          release_name: Version ${{steps.validate.outputs.version}}
          body: ${{steps.changelog.outputs.note}}
          draft: false
          prerelease: false
