name: 'push: master'

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        id: validate
        run: |
          VERSION=$(${{github.event.head_commit.message}} | sed -e '1d')
          if [[ $VERSION =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "::set-output name=version::${BASH_REMATCH[1]}"
          else
            exit 1
          fi
      - shell: bash
        name: Make tag test.
        run: |
          git tag ${{steps.validate.outputs.version}}
          git tag -d ${{steps.validate.outputs.version}}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.validate.outputs.version}}
          release_name: Version ${{steps.validate.outputs.version}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
