name: 'Repository initialize'
on:
  push:
    branches:
      - main
      - master

jobs:
  repository_initialize:
    name: Repository initialize
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'Initial commit')"
    steps:
      - uses: actions/checkout@master
      - name: Get @azu/github-label-setup
        run: yarn global add @azu/github-label-setup
      - name: Run github-label-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          `yarn global bin`/github-label-setup --token ${GITHUB_TOKEN} --labels ${GITHUB_WORKSPACE}/.github/labels.json